const categories = [
  { id: 0, name: "all" },
  { id: 1, name: "education and training" },
  { id: 2, name: "primary and preschool" },
  { id: 3, name: "secondary, youth, and other school" },
  { id: 4, name: "higher and university level" },
  { id: 5, name: "medical" },
  { id: 6, name: "safety" },
  { id: 7, name: "special education" },
  { id: 8, name: "adult education" },
  { id: 9, name: "sailing, driving, and other vehicles" },
  { id: 10, name: "e-learning" },
  { id: 11, name: "education facilities" },
  { id: 12, name: "staff and personnel" },
  { id: 13, name: "dogs and horse-riding" },
  { id: 14, name: "training programmes" },
  { id: 15, name: "seminars and personal development" },
  { id: 16, name: "vocational" },
  { id: 17, name: "industrial and technical" },
  { id: 18, name: "management" },
  { id: 19, name: "computer" },
  { id: 20, name: "environmental" },
  { id: 21, name: "health and first aid" },
  { id: 22, name: "language" },
  { id: 23, name: "tutorial" },
  { id: 24, name: "defense" },
];

export default categories;
